### ISSUE TITLE
Cyrillic names of files and folder are not read by the program with error

### ISSUE THREAD

**Issue by masaykh** [Vocaluxe/Vocaluxe#548]
Hi,

Error opening video file: d:\arc\ULTRASTAR_2018_RU\Zdob si Zdub  Видели ночь\Zdob si Zdub  Видели ночь.mp4
Unhandled error: stream is null   at Vocaluxe.Base.CVideo.Skip(CVideoStream stream, Single start, Single gap)
   at Vocaluxe.Screens.CScreenSing._LoadNextSong()
   at Vocaluxe.Base.CGraphics._FinishScreenFading()
   at Vocaluxe.Base.CGraphics.Draw()
   at Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop()
   at Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop()
   at Vocaluxe.CMainProgram._Run(String[] args)
   at Vocaluxe.CMainProgram.Main(String[] args)

**this does not happen with latin only path \ file names.**

Windows 10 Pro 20H2.
Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-61-g81c3233)

**Comment by Stefan1200-de** [comment]
Yes, this can happen, because we use an external library to load video files. It seems that this library is unable to open files with non latin filenames.

@lukeIam I remember, that we already had this issue some months ago. If you have some spare time someday, can you look at it? External C/C++ libraries are not my expertise. ;)

**Comment by masaykh** [comment]
I confirm, without video works good.

Could this external library be changed \ switched \ upgraded?

**Comment by Stefan1200-de** [comment]
We already upgraded it earlier this year.

**Comment by masaykh** [comment]
yup, found it already. so it either problem inside acinerella or in data which is passed to it.

Are you using unicode to pass path\ file names?

**Comment by masaykh** [comment]
@lukeIam  could you please take a look ?
